import Header from "@/components/Header";
import { currentUser } from "@clerk/nextjs/server";
import { Metadata } from "next";
import { redirect } from "next/navigation";
import React from "react";

export const metadata: Metadata = {
  title: "Mostafa Dev | Admin",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: "/logo/logo_MD.png",
    },
  },
};

const layout = async ({ children }: { children: React.ReactNode }) => {
  const user = await currentUser();
  if (user?.publicMetadata.role !== "admin") {
    redirect("/not-authorized");
  }
  return (
    <main>
      <Header />
      {children}
    </main>
  );
};

export default layout;
